-- SANTABIRRADB
-- USERS - PERMISOS
USE SANTABIRRADB;

-- Manager:

CREATE USER 'manager_user'@'%' IDENTIFIED BY 'ManPas001';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_COMPRAS_INSERTAR TO 'manager_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_COMPRAS_CONSULTAR TO 'manager_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_COMPRAS_ACTUALIZARFECHA TO 'manager_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_COMPRAS_ACTUALIZARCANTIDAD TO 'manager_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_COMPRAS_ELIMINAR TO 'manager_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_INSERTAR_INVENTORY TO 'manager_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_UPDATE_INVENTORY TO 'manager_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_DELETE_INVENTORY TO 'manager_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_insertarReserva TO 'manager_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_insertarReservaZona TO 'manager_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_actualizarFecha TO 'manager_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_actualizarHora TO 'manager_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_actualizarZona TO 'manager_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_actualizarStatus TO 'manager_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_actualizarPromocion TO 'manager_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_eliminarReserva TO 'manager_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_registrarAcompañantes TO 'manager_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_VENTAS_INSERTAR TO 'manager_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_VENTAS_ACTUALIZARCANTIDAD TO 'manager_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_VENTAS_ELIMINAR TO 'manager_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_VENTASD_ELIMINAR TO 'manager_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_VENTASD_INSERTAR TO 'manager_user'@'%';
GRANT SELECT ON SANTABIRRADB.V_COMPRAS_GASTOSPROVEEDOR TO 'manager_user'@'%';
GRANT SELECT ON SANTABIRRADB.VW_REPORTE_MINIMAS_EXISTENCIAS TO 'manager_user'@'%';
GRANT SELECT ON SANTABIRRADB.VW_REPORTE_INCIDENTES_CLIENTE TO 'manager_user'@'%';
GRANT SELECT ON SANTABIRRADB.VW_REPORTE_RESERVAS TO 'manager_user'@'%';
GRANT SELECT ON SANTABIRRADB.VW_REPORTE_RESERVAS_COMPLETADAS TO 'manager_user'@'%';
GRANT SELECT ON SANTABIRRADB.VW_REPORTE_VENTAS_PRODUCTOS TO 'manager_user'@'%';






-- vendedor:
CREATE USER 'seller_user'@'%' IDENTIFIED BY 'SellerPas001';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_VENTAS_INSERTAR TO 'seller_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_VENTAS_ACTUALIZARCANTIDAD TO 'seller_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_VENTAS_ELIMINAR TO 'seller_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_VENTASD_ELIMINAR TO 'seller_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_VENTASD_INSERTAR TO 'seller_user'@'%';
GRANT SELECT ON SANTABIRRADB.VW_REPORTE_VENTAS_PRODUCTOS TO 'seller_user'@'%';


-- promotor 
CREATE USER 'promotor_user'@'%' IDENTIFIED BY 'promotorPas001';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_insertarReserva TO 'promotor_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_insertarReservaZona TO 'promotor_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_actualizarFecha TO 'promotor_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_actualizarHora TO 'promotor_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_actualizarZona TO 'promotor_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_actualizarStatus TO 'promotor_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_actualizarPromocion TO 'promotor_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_eliminarReserva TO 'promotor_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_registrarAcompañantes TO 'promotor_user'@'%';

-- gestor_inventario

CREATE USER 'inventario_user'@'%' IDENTIFIED BY 'inventarioPas001';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_INSERTAR_INVENTORY TO 'inventario_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_UPDATE_INVENTORY TO 'inventario_user'@'%';
GRANT EXECUTE ON PROCEDURE SANTABIRRADB.SP_DELETE_INVENTORY TO 'inventario_user'@'%';
GRANT SELECT ON SANTABIRRADB.VW_REPORTE_MINIMAS_EXISTENCIAS TO 'inventario_user'@'%';


-- guardia
CREATE USER 'guardia_user'@'%' IDENTIFIED BY 'guardiaPas001';
GRANT SELECT, UPDATE,  INSERT, DELETE ON SANTABIRRADB.INCIDENT TO 'guardia_user'@'%';


